### ISSUE TITLE
Signal description close button is black until hover

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/www-covidcast#500] opened 2020-09-25 15:54 UTC
**Actual Behavior:**

When I open the signal description popup, I see this:

![Screen Shot 2020-09-25 at 11 36 38 AM](https://user-images.githubusercontent.com/711629/94286724-61ebc100-ff23-11ea-9067-9182d9b51930.png)

On hover, the X turns into a proper X.

**Steps to Reproduce the Bug:**

1. go to https://dev--cmu-delphi-covidcast.netlify.app/
2. click the "?" button

The problem tends to go away on hover, or even on map resizes and other events -- e.g. if I try to open the developer tools and track it down, the black fades away (with a smooth transition) before I can track down the problem

**Rating Scale (1 is minor, 7 is severe):**

4?

**Context**

- Browser: Firefox 80

**Comment by sgratzl** [comment] 2020-09-28 09:27
duplicate of #473

**Closed by sgratzl** 2020-09-28 09:27 UTC
Labels: bug
