### ISSUE TITLE
Show all dates loading issues

### ISSUE THREAD

**Issue by chinandrew** [cmu-delphi/www-covidcast#918] opened 2021-04-20 18:06 UTC
**Actual Behavior:**

When the  "Show All Dates" button is clicked, the graph expands but doesnt load. The spinner just spins and eventually says an error occurred. When it does work, the results are not consistent. I think it might be a timeout issues where occasionally some data is not retrieved correctly?

**Steps to Reproduce the Bug:**

1. go to https://delphi.cmu.edu/covidcast/summary/?region=24510&date=20210414
2. go to "Covid Cases Chart" and click "Show All Dates"
3. Wait and see what happens
**Expected behavior**

The graph expands and the full line chart (same one each time) displays when the "Show All Dates" button is clicked

**Screenshots**

In this video, I first show the error that displays after you've let it try for long enough, and then refresh and show it trying to load.

https://user-images.githubusercontent.com/20176218/115442056-6ed54800-a1c6-11eb-8c75-b143eb77aca5.mp4

In these screenshots, notice the gap that occurs in the second plot despite generating both within 5 minutes of each other.

![Screenshot from 2021-04-20 11-00-50](https://user-images.githubusercontent.com/20176218/115443221-d770f480-a1c7-11eb-8d9d-1b11222a7200.png)

![Screenshot from 2021-04-20 10-59-30](https://user-images.githubusercontent.com/20176218/115443223-d8098b00-a1c7-11eb-83f7-29686b8ecb81.png)

**Rating Scale (1 is minor, 7 is severe):**

5

**Context**

All on Ubuntu 20.04
- Chrome Version 90.0.4430.72 (64bit)  and Firefox 87.0 (64-bit) 

**Additional context**

**Comment by sgratzl** [comment] 2021-04-20 19:22
the corresponding request that fails is https://api.covidcast.cmu.edu/epidata/api.php?endpoint=covidcast&data_source=indicator-combination&signal=confirmed_7dav_incidence_prop&geo_type=county&time_values=20200201-20210415&time_type=day&geo_values=24003%2C24005&fields=geo_value%2Cstderr%2Ctime_value%2Cvalue

I assume that because the DB index is not used since multiple geo_values are given. However, don't know why it doesn't use it and I don't have access to DB to check why

**Comment by sgratzl** [comment] 2021-05-06 17:29
with the new index hint at staging it is way faster: https://staging.delphi.cmu.edu/epidata/api.php?endpoint=covidcast&data_source=indicator-combination&signal=confirmed_7dav_incidence_prop&geo_type=county&time_values=20200201-20210502&time_type=day&geo_values=24003%2C24005&fields=geo_value%2Cstderr%2Ctime_value%2Cvalue

**Comment by sgratzl** [comment] 2021-05-06 17:29
closing as wontfix since fixed in the api

**Closed by sgratzl** 2021-05-06 17:29 UTC
Labels: bug
