### ISSUE TITLE
Selected indicator gets lost in date change

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1200] opened 2022-12-08 23:08 UTC
When I'm on explore an indicator mode, with vaccine acceptance, since it's not available for the current day I get a warning at the top telling me it was last available on June 25.

![Screen Shot 2022-12-08 at 3 06 34 PM](https://user-images.githubusercontent.com/732541/206585924-d7c519ef-d077-4afa-9ef9-e64cf9916303.png)

But when I click on June 25, it takes me to covid cases.

![Screen Shot 2022-12-08 at 3 07 27 PM](https://user-images.githubusercontent.com/732541/206585969-17e7b3c8-2f53-41fa-903b-5500d550a7af.png)

Maybe it's that covid cases is the default but we should make sure that the selected indicator doesn't get lost in date changes.

**Comment by ryantibs** [comment] 2022-12-08 23:09
To be clear, I clicked on June 25 in the **orange text box** and that's what loses the vaccine acceptance indicator selection. When I just change the date in the date dropdown box (if I move back to June this way) then it keeps vaccine acceptance.

**Comment by melange396** [comment] 2024-12-19 20:16
closing as a duplicate of #1241

**Closed by melange396** 2024-12-19 20:16 UTC
Labels: bug
