### ISSUE TITLE
Map / Canvas Doesn't Display correctly

### ISSUE THREAD

**Issue by cgg-cmu** [cmu-delphi/www-covidcast#439] opened 2020-09-11 15:10 UTC
**Actual Behavior:**

_Release: 18.2_

On ios devices running ios < 12.4 the map and chart display doesn't work as expected. The map doesn't render and the UI tools are in a different alignment.

See images

**Steps to Reproduce the Bug:**

When I...

The visualization does not work as expected.

1. Go to covidcast.cmu.edu  in a device with safari or chrome on a device running ios 12.2 or older

**Expected behavior**

The site will function as it does in that same device running ios 13.

**Screenshots**

<img width="1327" alt="Screen Shot 2020-09-11 at 9 16 56 AM" src="https://user-images.githubusercontent.com/60197405/92942203-4a8adf00-f41f-11ea-9542-79bf6c8d6227.png">

For reference, this is Release 16
<img width="1327" alt="Screen Shot 2020-09-11 at 9 21 23 AM" src="https://user-images.githubusercontent.com/60197405/92942295-5ecedc00-f41f-11ea-9bfa-95bae9ea194f.png">
 

**Rating Scale (1 is minor, 7 is severe):**

5

**Context**

- Browser: IOs 12.1 , Safari / Chrome

**Additional context**

**Comment by sgratzl** [comment] 2020-09-30 10:48
@cgg-cmu please test again with the upcoming v1.9

**Comment by tildechris** [comment] 2020-10-07 20:13
@sgratzl is this able to be replicated with chrome devtools or do you need an actual iOS device?

**Comment by sgratzl** [comment] 2020-10-08 07:32
I cannot reproduce it since v1.8.2 That's why I asked for a confirmation that it is now working

**Comment by tildechris** [comment] 2020-10-08 13:00
Closing this as not reproducible.  I checked analytics and there are no recent iOS users who've come to the site with < 12.4.

**Closed by tildechris** 2020-10-08 13:00 UTC
Labels: bug
