### ISSUE TITLE
Top 10 time series plots get truncated

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#589] opened 2020-10-26 17:37 UTC
**Actual behavior:**

Time series plots for "Top 10" view get (erroneously) truncated on the y-axis.

**Steps to reproduce the bug:**

https://covidcast.cmu.edu/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20201019&signalType=value&encoding=color&mode=top10&region=42003

**Expected behavior:**

The y-axis should scale so that the dynamic range of the time series is contained within the plot (as it does in the small multiple time series panel, or the big time series panel, in the "Map Overview" view).

**Screenshots:**

Truncated time series plots in "Top 10" view:

![Screen Shot 2020-10-26 at 12 53 55 PM](https://user-images.githubusercontent.com/732541/97207306-41b45980-1790-11eb-9e0b-115c22b46d8b.png)

Here's what the first one looks like in the small multiples time sets panel of the "Map Overview" view:

![Screen Shot 2020-10-26 at 12 59 19 PM](https://user-images.githubusercontent.com/732541/97207392-54c72980-1790-11eb-8af4-d334628027c1.png)

**Rating scale (1 is minor, 7 is severe):**

2 or 3

**Comment by tildechris** [comment] 2020-10-26 17:44
I think #552 resolves this issue, which is currently included in the [release candidate](https://deploy-preview-581--cmu-delphi-covidcast.netlify.app/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20201019&signalType=value&encoding=color&mode=top10&region=42003).

Ryan, can you verify there?

**Comment by dlaliberte** [comment] 2020-10-26 18:16
While #552 resolves the issue, by scaling all the charts to avoid any truncation, it also potentially squashes the charts more than desired based on the maximum y value found across all the charts.

I also notice that the top-10 charts (in that screenshot) are interpolating across gaps of missing data.  e.g. the slopes in Lake County, CO.  I'm not sure if/when that was fixed, but I am not seeing it in my latest changes for #588.

**Comment by capnrefsmmat** [comment] 2020-10-26 18:27
Interpolating over missing data usually isn't desirable (see #385), so the top 10 charts indeed changed to ensure that doesn't happen.

**Comment by ryantibs** [comment] 2020-10-26 20:09
Chris, yes the release candidate addresses the truncation issue.  (And I agree with Alex that no interpolation over missing values is the right behavior.)

However, the release candidate (as Daniel points out) also blows up the y-axes to contain the 70% peak that Lake County hit many months ago, and in doing so, it becomes hard to read the time series today, at the end of October.  So if the point is to compare the time series *today* (the top 10 *today*), then I think we need to change something.  Perhaps, only show the last 4 weeks of data?  Or allow show the last 4 weeks by default in the top 10 view, but allow the user to load more history if they want.

**Comment by tildechris** [comment] 2020-10-26 20:28
See also discussion on #507.  Agree that setting a global max scale isn't useful because of the reason you mentioned (spikes can drown out recent movement).

I'll add this as a discussion topic at the team meeting this week to choose a method to improve this behavior.  I'm partial to re-scaling based on the (max in past x-days), truncating overflow values (but making the truncation obvious and explicit), and rescaling if the user mouses over the truncated date range.  Please chime in on #507 if you have ideas.

**Comment by dlaliberte** [comment] 2020-10-28 15:21
> Or allow show the last 4 weeks by default in the top 10 view, but allow the user to load more history if they want.

Always scaling the y axis based on the maximum y value in _some_ range of the x axis will **avoid the need to deal with truncation/clipping**.  But then we will have another problem: we will need to allow the user to **select a different date range** (for the x axis), by panning, or scrolling, possibly combined with zooming, or entering some date range.   

We may eventually **need such a date range selector anyway**, given the extended time that covid will remain active, and so the ever-growing timeline may need to be truncated in the horizontal direction so the user can focus on a narrower range of more recent dates, or inversely, to expand the range to see patterns over a longer timeframe.

One problem with avoiding the clipping is that the user may want to **simply ignore the clipping** (after knowing that it is happening) in order to **focus on the remainder of unclipped data** at all the other locations in the same date range.  If we always force rescaling to avoid clipping, the consequence is that some data might always be squashed in the presence of a higher peak.

Another approach is to allow the clipping but **let the user control the y-axis scaling to determine how much it is clipped**, or not.  This would be a vertical zoom control, perhaps with a slider on the top of the y-axis.

Here is what I would like to do: For maximum flexibility, we should allow clipping, render the clipped edge so it is clear, and then also provide controls for zooming/panning separately for x and y directions.   Auto scaling could be done as well to provide a good default, but then the user could always override.

**Comment by dlaliberte** [comment] 2020-10-28 17:17
Since this issue and #507 are mostly duplicates of each other, one could be marked as duplicate of the other.  But let's deal with the truncation here, and the auto-scaling and manual controls in #507.

**Comment by dlaliberte** [comment] 2020-10-29 03:20
Here is a reasonable approximation for one way to render the clipping.  

![image](https://user-images.githubusercontent.com/570125/97521133-47b66000-1973-11eb-94b4-4d492a100b0f.png)

- In the typical case, there wouldn't be nearly this much clipping going on.  I just forced the need for lots of clipping so I could do this rendering work.  
- I'm trying (and failing) to hide the gray line where the clipping occurs, so it should look even less like there is real data there.
- The top 10 page only shows one or two (side by side) indicators, so there is no need to worry about confusing overlapping clipped regions with multiple indicators in the same chart.  Solving that for a more general case might be useful, but we don't need it yet.

**Comment by tildechris** [comment] 2020-10-30 13:56
In your example, this wouldn't be the default scale of the chart right?  Because we'd scale the latest "neighborhood" so that we're not clipping any data in the past 14 days.

Also, I think that we should find a less busy indication than an up arrow for every clipped value.  I'd like to see an example that has one clipping indicator for the entire contiguous section of clipped values.

**Comment by dlaliberte** [comment] 2020-10-30 15:24
Right, this would not be typical.  In order to force the clipping, I actually cut the auto-computed scale (which avoids all clipping) in half. 

Yes, this visualization is too noisy.  Initially, I only succeeded in detecting the clipping and displaying _some_ indicator in the correct places.  That turned out to be harder than I expected.

Maybe a sequence of equally spaced icons, whether it is an up arrow or something else, would be clearer.  Not sure how to get vega to do that, but it seems possible.

One thing to keep in mind is that the "entire contiguous section of clipped values" can end up being many separate shorter sections, when the value crosses the threshold many times.

**Comment by dlaliberte** [comment] 2020-10-30 18:39
Here is a much cleaner visualization:

![image](https://user-images.githubusercontent.com/570125/97743894-b6530500-1abc-11eb-8bcd-fe087ac7dc92.png)

I'm not sure how the gray line where it is clipped ends up looking dashed, but I suspect it is an artifact of overlaying with the pink region above it.  Looks cool though.

**Comment by tildechris** [comment] 2020-10-30 19:17
Yes! I like this much better.  I had a couple of thoughts I was experimenting with:

1. It might be visually cleaner if we use a harpoon arrow instead of a full arrow

![image](https://user-images.githubusercontent.com/46794497/97747815-eac9bf80-1ac2-11eb-8ba3-a3b5ceb79ba9.png)

2. We could be very explicit by using a discontinuous axis symbol on the y axis 

![image](https://user-images.githubusercontent.com/46794497/97747869-f74e1800-1ac2-11eb-8d60-c49228a2a868.png)

Thoughts?

**Comment by dlaliberte** [comment] 2020-10-30 19:53
The harpoon arrows are pretty nice too, though there are not as many styles to choose from.

![image](https://user-images.githubusercontent.com/570125/97750789-d936e680-1ac7-11eb-87f9-568da81af949.png)

One thing I didn't anticipate is that a clipped value can be next to a null value, so the arrow is missing in one case in the above.

**Comment by dlaliberte** [comment] 2020-10-30 21:43
Overlaying marks on the axis could be challenging, because vega-lite wants to control the display of axes.  I don't know if we can make it deterministic, but I would like to find out whether it is possible.

**Comment by tildechris** [comment] 2020-11-05 14:01
I like the latest prototype.  @dlaliberte are you ready for this to be reviewed?

**Comment by dlaliberte** [comment] 2020-11-05 16:24
There are several issues, not all completed.

- The rendering of clipped lines is mostly completed.  That's just the rendering itself, when there is clipping.  But rendering the clipped lines makes all the following problems much more apparent.
- Making space above the chart to render the clipped lines requires a change in how top-padding is done, because the same small multiple chart is used in 3 different contexts.
- The neighborhood around the "current" (selected) date to check when computing the maximum across charts, is done, except I don't trust that I have the correct time span.
- Some charts use 7-day average data, and the maximum values are currently incorrectly computed.  Easily fixed, and I will make a separate PR for this.
- Extra refreshes of the charts don't always end up with the correct maximum value used in scaling the chart and clipping.  Slightly improved by debouncing the resize related refreshes globally.  More work is required to deal with the refreshes due to dynamic loading of the data.

**Comment by dlaliberte** [comment] 2020-11-11 18:14
FYI, the current design is simpler, by removing the arrows/harpoons.  See #614 for details.

**Closed by dlaliberte** 2020-11-11 18:14 UTC
Labels: bug
